@Runpay.API_HostAddress = https://localhost:7008

POST {{Runpay.API_HostAddress}}/api/contato
Content-Type: application/json

{
  "nome": "asdsadasdaddsa",
  "email": "sadads@asddsa",
  "telefone": "123123213",
  "cpf": "12322154323",
  "mensagem": "dsaadaddsadsa"
}

###
